Updated Chromatic specific documentation steps.
ChromaticHQ/ansible-sumocollector pull request #1
Opened 2017-07-30 17:24 UTC by sheyd

2017-07-31 14:14 UTC, markdorison requested changes

2017-07-31 14:14 UTC, markdorison commented on README.md
> +## Chromatic Specific Notes
Can we write this in a way that is not specific to "Chromatic", but just details the functionality that is present/needed here?

2017-08-08 06:26 UTC, ctorgalson reviewed
New content 👍 

Looks like [line 42](https://github.com/ChromaticHQ/ansible-sumocollector/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R42) should be outside the code block.

2017-08-08 14:23 UTC, markdorison approved these changes

2017-08-08 14:45 UTC, merged